apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka-aks-test
  namespace: r1-stampede
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: kafka-aks-test
    spec:
      imagePullSecrets:
        - name: acr-auth
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - name: kafka-aks-test
          image: r1k8sacrdev.azurecr.io/kafka-aks-test:v9
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-aks-test
  namespace: r1-stampede
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: kafka-aks-test